name: Podman Compose Remote Deployment
author: Alexander Raschke
description: A GitHub Action that supports docker-compose on remote hosts
inputs:
  remote_container_host:
    description: Remote container host, i.e. (user@host)
    required: true
  ssh_private_key:
    description: SSH private key used to connect to the docker host
    required: true
  args:
    description: Deployment command args.
    required: true
  remote_socket_path:
    description: remote path to podman socket. Default is /run/user/1000/podman/podman.sock
    required: false
  compose_file_name:
    description: Docker compose file used. Default is docker-compose.yml
    required: false
  ssh_port:
    description: The ssh port of the server. Default is 22
    required: false
  docker_login_password:
    description: The docker login password
    required: false
  docker_login_user:
    description: The docker login user
    required: false
  docker_login_registry:
    description: The docker login registry
    required: false

runs:
  using: docker
  image: docker://araschke/podman-remote-deployment-action:latest


branding:
  icon: send
  color: green

